# Stubs for django.db.models.base (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.utils.translation import ugettext_lazy as _
from .options import Options

def subclass_exception(name, parents, module, attached_to=None): ...

class ModelBase(type):
    def __new__(cls, name, bases, attrs): ...
    def copy_managers(cls, base_managers): ...
    def add_to_class(cls, name, value): ...
    _meta = ... # type: Options

class ModelState:
    db = ... # type: Any
    adding = ... # type: Any
    def __init__(self, db=None): ...

class Model:
    def __init__(self, *args, **kwargs): ...
    @classmethod
    def from_db(cls, db, field_names, values): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __hash__(self): ...
    def __reduce__(self): ...
    pk = ... # type: Any
    _meta = ... # type: Options
    def get_deferred_fields(self): ...
    def refresh_from_db(self, using=None, fields=None, **kwargs): ...
    def serializable_value(self, field_name): ...
    def save(self, force_insert=False, force_update=False, using=None, update_fields=None): ...
    def save_base(self, raw=False, force_insert=False, force_update=False, using=None, update_fields=None): ...
    def delete(self, using=None, keep_parents=False): ...
    def prepare_database_save(self, field): ...
    def clean(self): ...
    def validate_unique(self, exclude=None): ...
    def date_error_message(self, lookup_type, field_name, unique_for): ...
    def unique_error_message(self, model_class, unique_check): ...
    def full_clean(self, exclude=None, validate_unique=True): ...
    def clean_fields(self, exclude=None): ...
    @classmethod
    def check(cls, **kwargs): ...

def method_set_order(ordered_obj, self, id_list, using=None): ...
def method_get_order(ordered_obj, self): ...
def make_foreign_order_accessors(model, related_model): ...
def simple_class_factory(model, attrs): ...
def model_unpickle(model_id, attrs, factory): ...
def unpickle_inner_exception(klass, exception_name): ...
